name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Set TIMESTAMP
      id: date
      run: echo "::set-output name=timestamp::$(date +%s)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wdxhl1024/pytorch_self:${{ steps.date.outputs.timestamp }}
    - name: Push Docker image to Docker Hub
      run: docker push wdxhl1024/pytorch_self:${{ steps.date.outputs.timestamp }}
