name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Set TIMESTAMP
      id: date
      run: echo "::set-output name=timestamp::$(date +%s)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wdxhl1024/pytorch_self:${{ steps.date.outputs.timestamp }}
    - name: Push Docker image to Docker Hub
      run: docker push myusername/myapp:${{ steps.date.outputs.timestamp }}
